### ISSUE TITLE
bool fields

### ISSUE THREAD

**Issue by veryevilzed** [Neopallium/lua-pb#23]
proto
-----
message Msg {
    required bool fld = 1;
}

code
----
msg = Msg()
msg.fld = false
d,err = msg:Serialize()

err is ```Missing required field: fld```

**Comment by daurnimator** [comment]
Related to #10?

**Comment by veryevilzed** [comment]
No, 
unpack ```required bool = false``` field also doesn't work

**Comment by veryevilzed** [comment]
```
pb/standard/message.lua@233
--- if val then
+++ if val ~= nil then
```

**Comment by Neopallium** [comment]
pushed fix.  Thanks
