### ISSUE TITLE
Parsing Caffe's proto

### ISSUE THREAD

**Issue by vadimkantorov** [Neopallium/lua-pb#24]
I've tried parsing https://github.com/BVLC/caffe/blob/master/src/caffe/proto/caffe.proto.

The first error was first line, not supporting `syntax = "proto2"`. When I comment it, the next error is line 45: `optional string type = 1 [default = 'constant'];`.

If it's not hard to fix, lua-pb together with https://github.com/google/upb could be very useful to convert Caffe neural net models to Torch.

Thanks!

**Comment by Neopallium** [comment]
Fix parsing errors for the `caffe.proto` file.

I don't understand how you want to use `lua-pb` together with `upb`.

**Comment by vadimkantorov** [comment]
`upb` doesn't support parsing raw \*.proto files, so I was thinking to parse `caffe.proto` with lua-pb, and then build the `upb` schema in memory.

**Comment by Neopallium** [comment]
I didn't see an API in `upb` for creating the in memory schema.  If they do provide that, then it might be possible to use `upb` as a backend to `lua-pb`.

Open another issue for `upb` integration.  Also if you can find some information about building the schema in memory.

**Comment by vadimkantorov** [comment]
Yep, lua's support in `upb` isn't well documented. If I understand well, their [MessageDefinition API](https://github.com/google/upb/blob/master/tests/bindings/lua/test_upb.pb.lua#L14) would be the one.
