### ISSUE TITLE
int64_t cdata/8 bytes serialize error

### ISSUE THREAD

**Issue by garinyan** [Neopallium/lua-pb#25]
package proto;
message PersonLogInfo {
  optional int64 id = 1; 
}

Set id=8377627783044821654LL and serialize it, then got 65450217135436438LL as the deserialization result.

Same issue using 8 bytes("\116\67\80\21\4\212\114\150").

Is it a bug or an known issue? Look forward to your reply and thank you.

**Comment by Neopallium** [comment]
This might be the same issue as #26.

**Comment by Neopallium** [comment]
Fix push.  The problem was with using LuaJIT's bitops to cast large 64bit value to 32bits for encoding.

```
local bit = require"bit"

-- old casting logic.  Works in Lua, but not LuaJIT
print(string.format("0x%08X", bit.band(0x7443501504D47400, 0xFFFFFFFF)))

-- new casting logic.  Works in both Lua & LuaJIT
print(string.format("0x%08X", (0x7443501504D47400 % 0x100000000)))

```
