### ISSUE TITLE
Serialising Int64 type returns unexpected data

### ISSUE THREAD

**Issue by ronan-skyscanner** [Neopallium/lua-pb#26]
I am using this library on Lua5.1, and have found that suddenly the timestamps passed in myt messages have come back deserialised wrong.

Assume this schema:
```
package apicall
message DateTime {
    optional int64 unix_time_millis = 1; // UNIX timestamp in MILLIS
}
```

And this code:
```
    local event_timestamp = apicall.DateTime()
    event_timestamp.unix_time_millis = value
    local serialized = event_timestamp:Serialize()
    local deserialized = apicall.DateTime():Parse(serialized)
    local is_valid = value == deserialized['._data'].unix_time_millis
```

Using `1477221297000` as a value will return is_valid = true, but using `1477566933000` as value return is_valid = false.
That is the serialisation followed by of the Int64 type doesn't return the value that was initially passed in.

**Comment by Neopallium** [comment]
The problem happens with any numeric value that has bit 32 set.  When encoding/decoding 64bit numeric values lua-pb splits the value into upper/lower 32bits.  It looks like the code is processing the lower 32bits as a signed value and incorrectly decoding bit 32.

**Comment by Neopallium** [comment]
Fixed pushed.  The issue was encoding the lower 32 bits of large 64bit ints.  The code was doing variable length encoding of the lower 32 bits and not encoding a full 4 bytes when there was higher bits still to be encoded.
